import { Link } from 'react-router-dom'
import PageHero from '../components/PageHero'
import Reveal from '../components/Reveal'
import Cta from '../components/Cta'
import { LEADERS } from '../data/site'
import { IMG } from '../data/images'
import useTitle from '../hooks/useTitle'

const VALUES = [['Transparency', 'Communicate clearly and avoid unnecessary complexity.'], ['Relevance', 'Recommend opportunities based on the client’s actual requirement.'], ['Professionalism', 'Maintain a structured, responsive and respectful experience.'], ['Experience', 'Bring practical business and market understanding into each conversation.'], ['Relationships', 'Build trust that extends beyond a single transaction.']]
const STEPS = [['Understand', 'Location, purpose, property type, budget, timing and priorities.'], ['Shortlist', 'Identify relevant opportunities based on the requirement.'], ['Discuss', 'Provide clear information and answer practical questions.'], ['Coordinate', 'Support property discussions, visits and next-step communication.'], ['Stay Connected', 'Maintain a long-term relationship for future property needs.']]

export default function AboutUs() {
  useTitle('About Nobelcrest Properties | Real Estate Team India & Dubai', 'Meet the people behind Nobelcrest Properties and learn how experience, transparent advice and client-first service shape our real estate work across India and Dubai.', [
    { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: `${window.location.origin}/` }, { '@type': 'ListItem', position: 2, name: 'About Us', item: window.location.href }] },
    ...LEADERS.filter((person) => !person.name.startsWith('Ayesha')).map((person) => ({ '@context': 'https://schema.org', '@type': 'Person', name: person.name, jobTitle: person.role, worksFor: { '@type': 'Organization', name: 'Nobelcrest Properties LLP' } })),
  ])
  return <>
    <PageHero title="Built on Experience. Guided by Trust." sub="Professional real estate guidance shaped by clarity, market understanding and long-term relationships." img={IMG.lobby} crumb="About Us" />
    <section><div className="wrap editorial-split"><Reveal><span className="eyebrow">About Nobelcrest Properties LLP</span><h2>Real estate is personal. The guidance should be too.</h2></Reveal><Reveal><p className="lead">Nobelcrest is a real estate consultancy helping clients navigate property decisions with clarity and professional communication.</p><p>Our work spans residential and commercial real estate across India and Dubai, with a current India focus on Maharashtra, primarily Mumbai and Pune. We begin by understanding the client’s requirement and the context behind it.</p><Link className="text-link" to="/services">Explore Our Services</Link></Reveal></div></section>
    <section className="cream"><div className="wrap"><div className="vision-grid"><Reveal><span className="number">01</span><span className="eyebrow">Our Mission</span><h3>Make property decisions clearer.</h3><p>Provide relevant property guidance, professional coordination and transparent communication across every stage of the relationship.</p></Reveal><Reveal><span className="number">02</span><span className="eyebrow">Our Vision</span><h3>Build a trusted cross-market presence.</h3><p>Connect clients with meaningful residential and commercial property opportunities across India and Dubai.</p></Reveal></div></div></section>
    <section><div className="wrap"><div className="section-head"><span className="eyebrow">What Guides Our Work</span><h2>Principles that shape every conversation.</h2></div><div className="values-row">{VALUES.map(([title, text]) => <Reveal key={title}><h3>{title}</h3><p>{text}</p></Reveal>)}</div></div></section>
    <section className="dark-section"><div className="wrap"><div className="section-head"><span className="eyebrow">Our Approach</span><h2>Five thoughtful steps.</h2></div><div className="process">{STEPS.map(([title, text], i) => <Reveal key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p></Reveal>)}</div></div></section>
    <section><div className="wrap"><div className="section-head"><span className="eyebrow">Leadership &amp; Team</span><h2>Experience behind every conversation.</h2><p>Leadership experience across real estate, business, construction, project development, administration and client service in India and the UAE.</p></div><div className="leaders">{LEADERS.map((person, i) => <Reveal className="leader" key={person.name}><div className="leader-mark">{String(i + 1).padStart(2, '0')}</div><div><p className="role">{person.role}</p><h3>{person.name}</h3><p className="experience">{person.experience}</p><p>{person.copy}</p>{person.name.startsWith('Ayesha') && <ul className="strengths"><li>Administrative and property operations expertise</li><li>Real estate sales and client management</li><li>Property buying, selling and leasing</li><li>Documentation and tenancy procedures</li><li>Transparent client follow-up</li><li>Negotiation and coordination skills</li></ul>}</div></Reveal>)}</div><div className="confirmation-note"><b>Pre-launch confirmation:</b> Confirm Ayesha’s final designation and whether this section should be titled “Leadership” or “Leadership &amp; Team”.</div></div></section>
    <Cta title="Start with a conversation." text="Tell us the market, property type and requirement you are considering. We will help you understand the next step." />
  </>
}
