import { Link, useParams } from 'react-router-dom'
import { COMPANY, VERIFIED_PROJECTS } from '../data/config'
import PageHero from '../components/PageHero'
import Cta from '../components/Cta'
import useTitle from '../hooks/useTitle'

export default function ProjectDetail() {
  const { category, slug } = useParams()
  const project = VERIFIED_PROJECTS.find((item) => item.slug === slug && (item.propertyType === category || item.requirement === category))
  const related = project ? VERIFIED_PROJECTS.filter((item) => item.slug !== project.slug && (item.city === project.city || item.propertyType === project.propertyType || item.requirement === project.requirement)) : []
  const enquiryQuery = project ? new URLSearchParams({ property: project.name, category: project.propertyType, requirement: project.requirement === 'sale' ? 'buy' : project.requirement, city: project.city }).toString() : ''
  const canonicalPath = project ? `/projects/${project.propertyType}/${encodeURIComponent(project.slug)}` : undefined
  const schemas = project ? [{ '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: `${window.location.origin}/` }, { '@type': 'ListItem', position: 2, name: 'Projects', item: `${window.location.origin}/projects` }, { '@type': 'ListItem', position: 3, name: project.name, item: `${window.location.origin}${canonicalPath}` }] }] : []
  useTitle(project ? `${project.name} in ${project.location} | ${project.propertyType} | Nobelcrest` : 'Property Not Published | Nobelcrest', project ? project.description : 'This property is not currently published with verified information.', schemas, { noindex: !project, canonicalPath })
  if (!project) return <div className="not-found"><div><span className="crest-symbol">NC</span><p className="eyebrow">Verified properties only</p><h1>This property is not currently published.</h1><p>Property pages become available only after the project name, location, specifications, availability, media and regulatory information have been verified.</p><div className="actions"><Link className="btn" to="/projects">Browse Opportunities</Link><Link className="btn line" to="/contact-us">Discuss Your Requirement</Link></div></div></div>
  return <><PageHero title={`${project.name}, ${project.location}`} sub={project.description} img={project.heroImage} imgAlt={project.imageAlt} crumb={<><Link to="/projects">Projects</Link> / {project.name}</>} /><section><div className="wrap project-detail"><div><span className="eyebrow">Property Overview</span><h2>{project.overviewTitle || 'Key property information'}</h2><p>{project.overview}</p>{project.features?.length > 0 && <><h3>Features &amp; Amenities</h3><ul className="check-list light-list">{project.features.map((feature) => <li key={feature}>{feature}</li>)}</ul></>}</div><aside><h3>Verified Facts</h3><dl>{Object.entries(project.facts || {}).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><Link className="btn" to={`/contact-us?${enquiryQuery}`}>Enquire About This Property</Link>{COMPANY.phone && <a className="btn line" href={`tel:${COMPANY.phone}`}>Call Nobelcrest</a>}{COMPANY.whatsapp && <a className="btn line" href={`https://wa.me/${COMPANY.whatsapp.replace(/\D/g, '')}?text=${encodeURIComponent(`Enquiry about ${project.name}`)}`} target="_blank" rel="noreferrer">WhatsApp Nobelcrest</a>}</aside></div></section>
    <section><div className="wrap related-browse"><h2>Explore Related Categories</h2><div className="filter-links"><Link to={`/projects/${project.propertyType}`}>{project.propertyType}</Link><Link to={`/projects/${project.requirement}`}>{project.requirement}</Link></div>{related.length > 0 && <><h3>Related Properties</h3><div className="cards">{related.map((item) => <article className="card" key={item.slug}><img src={item.image} alt={item.imageAlt} loading="lazy" /><div className="b"><p className="eyebrow">{item.city} · {item.propertyType} · {item.requirement}</p><h3>{item.name}</h3><p>{item.description}</p><Link className="text-link" to={`/projects/${item.propertyType}/${item.slug}`}>View Details</Link></div></article>)}</div></>}<div className="filter-links"><Link to={`/projects?city=${encodeURIComponent(project.city)}`}>More in {project.city}</Link><Link to="/contact-us">Contact Nobelcrest</Link></div></div></section>
    <Cta title="Would You Like to Discuss This Property?" text="Share your requirement and the Nobelcrest team can coordinate the next conversation." /></>
}
